/*
gcc -o libHelloImpl.dylib -lc -shared -I$(/usr/libexec/java_home)/include -I$(/usr/libexec/java_home)/include/darwin com_normee_Hello.c
gcc -o libHelloImpl.so -lc -shared -I/usr/lib/jvm/java/include -I/usr/lib/jvm/java/include/linux com_normee_Hello.c -fPIC
*/
#include <stdio.h> 
#include "com_normee_Hello.h"	// generated by javah

JNIEXPORT void JNICALL Java_com_normee_Hello_sayHi 
(JNIEnv *env, jobject obj, jstring who, jint times) { 
	jint i; 
	jboolean iscopy; 
	const char *name; 
	name = (*env)->GetStringUTFChars(env, who, &iscopy); 
	for (i = 0; i < times; i++) {
		printf("Hello %s\n", name);
	}
}